baseURL = 'https://cdecl.github.io/'
languageCode = 'ko-kr'
title = 'cdeclog'
theme = 'PaperMod'
timeZone = "Asia/Seoul"

[services.googleAnalytics]
  id = "G-VQQHHYPN7K"

[outputs]
home = ['HTML', 'RSS', 'JSON']

[pagination]
pagerSize = 10

[params]
author = "Byung Kyu KIM"
description = "cdecl's Dev.Ops Blog"
mainSections = ["dev", "devops", "post"]
defaultTheme = "auto"
displayFullLangName = true
ShowToc = true
TocOpen = false
TocSidebar = true
ShowCodeCopyButtons = true
ShowBreadCrumbs = true  


[params.homeInfoParams]
Title = "CDECLOG"
Content = "✔ Write down what comes to mind :: Bright size life "

[[params.socialIcons]]
name = "github"
url = "https://github.com/cdecl"


[[params.socialIcons]]
name = "website" # Using 'website' or 'link' as a generic icon
url = "https://cdecl.tistory.com/"

[params.comments]
enable = true

[params.profileMode]
enabled = false

[params.cover]
hiddenInList = false
hiddenInSingle = false

[params.ToC]
enable = true
auto = true

[frontmatter]
date = [':filename', ':default']

[permalinks.page]
posts = "/:sections[last]/:slug/"

[taxonomies]
tag = "tags"
category = "categories"

[markup]
tableOfContents = { startLevel = 2, endLevel = 6 }

[markup.goldmark.renderer]
unsafe = true
hardWraps = false

[markup.highlight]
style = "dracula"  # 또는 "github", "dracula" 등

[outputFormats.searchindex]
mediaType = "application/json"
baseName = "searchindex"

ignoreLogs = ["warning-goldmark-raw-html"]


[[menu.main]]
name = "Dev"
url = "dev/"
weight = 5

[[menu.main]]
name = "DevOps"
url = "devops/"
weight = 6


[[menu.main]]
name = "Archive"
url = "archives/"
weight = 10

[[menu.main]]
name = "Search"
url = "search/"
weight = 20

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 30
